### ISSUE TITLE
Decision about the nature of the project

### ISSUE THREAD

**Issue by mauricebasement** [Robottiker/robottiker.github.io#1]
There are various ideas how the project could be realized; a decison needs to be made:

The most fundamental decesion is, wheter the settelement should remain movable or not.
A moveable structure allows to rent a property, otherwise there is a risk of loss of investments in infrastructure, when moving to another property. As well there are legal issues with building the container based settlement, on land. A possible way to avoid legal issues when building up a moveable structure is to rent a factory, and start to build the shipping container based modules in it.

Should the settlement be compeltley movebale or not?

**Comment by ottiker** [comment]
+1 for completely movable. At least in the evaluation phase. Maybe we find out that it's to expensive/complicated. But we should plan with movable structures in mind.

**Comment by mauricebasement** [comment]
moved to other repository
