### ISSUE TITLE
Defining Modules

### ISSUE THREAD

**Issue by mauricebasement** [Robottiker/robottiker.github.io#2]
We have to create a list with all modules that are needed for the settlement. The infrastructure document that i uploaded on the former github project page, can be taken as a basis.

**Comment by michaelseverin** [comment]
Deine Erfahrungen z.B bei der Abwasserverwendung oder der Hydroponic Geschichte sind gold wert. Ich finde, dort wo wir bereits Erfahrungen und Wissen gesammelt haben, sollten wir weitergehen. Also Hydrophonic klar vor Farmbot.  I started to create a List of the different modules under "Defining Module Types" in the "settlement" repository.

**Comment by mauricebasement** [comment]
issue continued in other repository; closed
